import React , { useState, useEffect } from 'react'

import { Card ,Loader ,FormField } from '../components'
import '/src/style.css';

const RenderCards = ({data , title}) =>{
    if(data?.length > 0){
        return data.map((post) => <Card key={post._id} {...post}/>)
    }
    return(
        <h2 className='mt-5 font-bold text-[#6449ff] text-xl uppercase'>
         {title}</h2>
    )
}

const home = () => {
  
    const [loading, setLoading] = useState(false);
    const [allPosts, setAllPosts] = useState(null);
    const [searchText, setsearchText] = useState('');
    const [searchedResults, setSearchedResults] = useState(null);
    const [SearchTimeout, setSearchTimeout] = useState(null);


    useEffect(() => {
        const fetchPosts = async () => {
            setLoading(true);

            try {
                const response = await fetch('http://localhost:8080/api/v1/post',{
                    method: 'GET',
                    headers: {
                      'Content-Type': 'application/json',
                    },
                  })
    
                  if(response.ok) {
                    const result = await response.json();
    
                    setAllPosts(result.data.reverse());
                  }
            } catch (error) {
                alert(error);
            }finally {
                setLoading(false);
            }
        }

        fetchPosts();        
    }, []);

    const handleSearchChange = (e) => {
        setsearchText(e.target.value);

        setSearchTimeout(
            setTimeout(() => {
                const searchResults = allPosts.filter((item) => item.name.toLowerCase()
                .includes(searchText.toLowerCase()) || item.
                prompt.toLowerCase().includes(searchText.toLowerCase()));
            
                
                setSearchedResults(searchResults);
    
            }, 500)
        );

    }
  
    return (
    <section className='max-w-7xl mx-auto'>
        <div>
            <h1 className='style-text font-extrabold
            text-[32px]'>The Community Showcase</h1>
            <p className='style-text  mt-2 text-[16px]
            max-w[500px]'>Browse through a collection of
            imaginative and visually stunning images 
            generated by DALL-E AI</p>
        </div>
        <br></br>
        <br></br>
        <br></br>
        <span className='bold text-white'>SEARCH POSTS</span>
        <div className='mt-1'>
             <FormField 
            
             type="text"
             name="text"
             placeholder="Search Posts"
             value={searchText}
             handleChange={handleSearchChange}
             />
        </div>

        <div className='mt-10'>
            {loading ? (
                <div className='mt-60 flex rotate-90 justify-center
                items-center'>
                    <Loader/>
                </div>
            ) : (
                <>
                 {searchText && (
                    <h2 className='font-medium text-[#666e75] text-xl mb-3'>
                        Showing results for <span className='text-[#222328]'>{searchText}</span>
                    </h2>
                 )}
                 <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-
                 cols-2 grid-cols-1 gap-3'>
                    {searchText ? 
                    <RenderCards 
                        data={searchedResults}
                        title="No search results found!"        
                    />
                    : <RenderCards
                        data = {allPosts}
                        title="No posts Found"
                    />
                    }
                 </div>
                </>
            )

            }
        </div>
    </section>
  )
}

export default home